### ISSUE TITLE
[Improvement] Validation composability

### ISSUE THREAD

**Issue by jaypaik** [erc6900/resources#36]
Currently, the standard only allows the application of a single validation function on an execution function. If you want to use a different validation mechanism (e.g., passkey) for that same function, you'd have to uninstall the plugin that installed the existing validation function, and then install a new plugin that applies passkey validation.

This inflexibility is one of the motivators behind https://github.com/erc6900/resources/issues/4, which would enable multiple different validation functions to be applied for a single execution function, and have the caller be able to specify which validation function to use if there are multiple ways to gain authorization for a given function. Practically, this would enable users to install multiple different "ownership" plugins and be able to auth into the account in different ways:
- Install `EOAPlugin` to validate signatures from EOAs.
- Install `PasskeyPlugin` to validate signatures from passkeys.
- Install `MultisigPlugin` to validate composite signatures from multiple signers.

Note that each of these plugins houses its own set of **signers**, which are tightly coupled to signature verification methods defined within the plugin. For example, signers A and B, stored in `EOAPlugin` are always verified using `ecrecover`, and signers C, D, and E, stored in `MultisigPlugin` are authorized if 2 of 3 signatures are valid EOA or ERC-127 signatures.

What if we wanted to support something like a 5-of-9 multisig, in which 3 of the signers are validated with EOA signatures and the rest are validated with passkey signatures? We _could_ build a new `MultisigPlugin` that can handle these two different types of signers. But is there a better way to handle this that can decouple **owners** from the validation mechanism used?

Some definitions, to help illustrate this (h/t @noam-alchemy):
- A **signer** is a private key with a certain validation scheme.
- An **owner** is a transformation across N >= 1 signers, in other words, an entity authorized to run an executable.
- An **executable** is an action taken by an authorized owner.

And some examples:
- For an account that authorizes calls from singular EOAs:
  - Signer: each signer is an EOA (k1) private key.
  - Owner: each signer is an owner.
  - Executable: any function on the account.
- For an account that authorizes calls from multisig:
  - Signer: each signer has one associated signature validation scheme (e.g., r1, k1, etc.).
  - Owner: there is one owner, which is the aggregation of m of n signers.
  - Executable: any function on the account.
- For an account that authorizes calls for different transfer thresholds:
  - Signer: each signer has one associated signature validation scheme (e.g., r1, k1, etc.).
  - Owner: there are two owners (one can be an EOA owner, the other can be a 2-of-2 multisig).
  - Executable: Owner A can initiate any transaction up to $X, but only owner B can initiate transactions >$X.
  
While ERC-6900 already has the ability to apply different validation functions to different execution functions (decoupling of **owner** and **executable**), there isn't a clear way to separate **signers** and **owners**. It would be worth exploring this to increase the flexibility of plugins and reduce storage fragmentation of owners across multiple plugins.

**Comment by huaweigu** [comment]
I feel like **Owner** is more like a `Permissioned/Authorized` **Operator/Executor** within the context

**Comment by fangting-alchemy** [comment]
PR: https://github.com/erc6900/reference-implementation/pull/96
